pipeline {

    agent any

    stages {

        stage('Init') {
            steps {
                script {
                    sh 'docker --version'
                    sh 'docker images'
                    sh 'aws --version'
                }
            }
        }

        stage('Build + Deploy') {
            steps {
                script {
                    sh 'docker build --pull -t "experiment-nginx:latest" -f ./ci/Dockerfile .'
                    sh 'docker tag "experiment-nginx:latest" "769910020948.dkr.ecr.eu-west-1.amazonaws.com/experiment-nginx:test3"'
                    sh '$(aws ecr get-login --region "eu-west-1" --no-include-email)'
                    sh 'docker push "769910020948.dkr.ecr.eu-west-1.amazonaws.com/experiment-nginx:test3"'
               }
            }
        }

    }

}